accessibilityJob: false
alwaysRunPostSteps: false
appium: false
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
captureScreenRecordingForScenarios: false
codeDirectory: goodguys_playwright
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 15
cypress: false
differentialUpload:
    enabled: false
    forcedDisabled: false
    ttlHours: null
dynamicAllocation: false
env:
    COMMON_CONFIG_FILE: env/common.env
    RUN_ON_LAMBDATEST: "true"
    browser: MicrosoftEdge
    tag: dev
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        avoidAppLaunch: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalTimeout: 90
jobID: 05d9b468-8f75-4bc8-a67a-3c95e8b193fb
jobLabel:
    - playwright-VanillaJS
    - win
    - autosplit
    - good_guys
    - firefox
key: dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh
localHTTPProxy: ""
maxRetries: 1
maxRetriesPreSteps: 0
meta: {}
partialReports:
    type: json
    location: reports/
    frameworkName: cucumber
    email:
        to: []
        metaInfo: []
        linkValidity: 0
    configPath: ""
    configPathURL: ""
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - npm install
    - npx playwright install
preDirectives:
    commands:
        - npm install
        - npx playwright install
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: ""
    name: ""
    type: default
projectpath: ""
regionConfig: []
report: true
runson: win11
slackChannel: ""
sourcePayload:
    verifySSL: true
storageType: ""
testDiscovery:
    args:
        featureFilePaths: src/features
        frameWork: javascript
        specificTags:
            - '@dev'
    autosubset: true
    command: snooper --specificTags=@dev --featureFilePaths=src/features --frameWork=javascript
    mode: dynamic
    type: automatic
testDiscoveryResultV3: []
testRunnerCommand: npm run cucumber -- --profile dev $test ; node reports.js
testSuiteStep: 90
testSuiteTimeout: 90
testSuites: []
testType: playwright
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
uploadArtefacts:
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: Executed-Job-Artifacts
      path:
        - reports/**
uploadArtifacts:
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: Executed-Job-Artifacts
      path:
        - reports/**
user: shubhamr
version: "0.1"
waitForArtefactsUpload: false
